/** DO NOT MODIFY THIS FILE, ITS IS AUTOMATICALLY GENERATED ON EACH BUILD! **/

// Version numbers
#define BUILD_MAJOR_VERSION 0
#define BUILD_MINOR_VERSION 1
#define BUILD_PATCH_VERSION 0

// Build
#define BUILD_BUILD_NUMBER 133
#define BUILD_BUILD_DATE "Monday, 11 November 2019"
#define BUILD_BUILD_TIME "13:19:31"

// Git
#define BUILD_GIT_HASH "e364b14"
