/** DO NOT MODIFY THIS FILE, ITS IS AUTOMATICALLY GENERATED ON EACH BUILD! **/

// Version numbers
#define BUILD_MAJOR_VERSION 0
#define BUILD_MINOR_VERSION 1
#define BUILD_PATCH_VERSION 0

// Build
#define BUILD_BUILD_NUMBER 80
#define BUILD_BUILD_DATE "Sunday, 10 November 2019"
#define BUILD_BUILD_TIME "05:18:01"

// Git
#define BUILD_GIT_HASH "52b3694"
