/** DO NOT MODIFY THIS FILE, ITS IS AUTOMATICALLY GENERATED ON EACH BUILD! **/

// Version numbers
#define BUILD_MAJOR_VERSION 0
#define BUILD_MINOR_VERSION 1
#define BUILD_PATCH_VERSION 0

// Build
#define BUILD_BUILD_NUMBER 119
#define BUILD_BUILD_DATE "Sunday, 04 October 2020"
#define BUILD_BUILD_TIME "03:19:44"

// Git
#define BUILD_GIT_HASH "b5abd61"
